# Generated by Django 2.1 on 2019-03-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryprofile',
            name='dateOfEstablishment',
            field=models.CharField(max_length=30, null=True, verbose_name='Establishment'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='libraryMembership',
            field=models.CharField(max_length=30, null=True, verbose_name='Membership'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='libraryPolicy',
            field=models.CharField(max_length=30, null=True, verbose_name='Library Policy'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='librarySymbol',
            field=models.FileField(blank=True, null=True, upload_to='LibraryProfile/'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='librarywebsite',
            field=models.URLField(max_length=250, null=True, verbose_name='website'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='nameOfLibrary',
            field=models.CharField(max_length=30, null=True, verbose_name='Library Name'),
        ),
        migrations.AddField(
            model_name='libraryprofile',
            name='time',
            field=models.CharField(max_length=30, null=True, verbose_name='Library Time'),
        ),
    ]
