# Generated by Django 2.1 on 2019-03-13 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmodule', '0002_auto_20190313_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfSeller', models.CharField(max_length=30, null=True, verbose_name='Name')),
                ('sellerAddress', models.CharField(max_length=30, null=True, verbose_name='Address')),
                ('sellerContactNumber', models.CharField(max_length=30, null=True, verbose_name='Mobile No')),
                ('selleremail', models.EmailField(max_length=70, null=True, unique=True, verbose_name='E-mail')),
                ('sellerProfile', models.FileField(null=True, upload_to='sellerProfile/')),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
