# Generated by Django 2.1 on 2019-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_auto_20190313_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='selleremail',
            field=models.EmailField(max_length=70, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='sellerProfile',
            field=models.FileField(blank=True, null=True, upload_to='sellerProfile/'),
        ),
    ]
