# Generated by Django 2.1 on 2019-03-14 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmodule', '0005_auto_20190313_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryAddBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=30, null=True, verbose_name='Book Name')),
                ('bookLanguage', models.CharField(max_length=30, verbose_name='Language')),
                ('bookBinding', models.CharField(error_messages={'required': 'Please enter your name'}, max_length=30, verbose_name='Binding')),
                ('bookISBN', models.CharField(max_length=30, verbose_name='ISBN')),
                ('bookGener', models.CharField(max_length=30, verbose_name='Genre')),
                ('bookEdition', models.IntegerField(verbose_name='Edition')),
                ('bookPages', models.IntegerField(verbose_name='Pages')),
                ('bookStock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=30, verbose_name='InStock')),
                ('bookImage', models.FileField(blank=True, upload_to='documents/%Y/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
