# Generated by Django 2.1 on 2019-03-15 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0006_libraryaddbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryaddbook',
            name='aboutAuthor',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='About the Author'),
        ),
        migrations.AddField(
            model_name='libraryaddbook',
            name='bookSummary',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Summary Of The Book'),
        ),
    ]
