# Generated by Django 2.0.13 on 2019-03-27 14:49

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0009_useraddbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryprofile',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
