# Generated by Django 2.0.13 on 2019-04-01 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0011_libraryaddbook_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryaddbook',
            name='position',
        ),
        migrations.RemoveField(
            model_name='libraryprofile',
            name='position',
        ),
    ]
